echo Adding AWS environment variables;
export AWS_ACCESS_KEY_ID="Key here";
export AWS_SECRET_ACCESS_KEY="Key here";
pwd;
echo Changing directory;
cd ${WORKSPACE};
terraform init;
terraform plan;
terraform apply --auto-approve;
echo Terraform script completed!;